---
{{- if and .Values.zabbixweb.sslcert .Values.zabbixweb.sslkey .Values.zabbixweb.dhparam }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "web.fullname" . }}-ssl
  labels:
    app: {{ template "web.name" . }}
    chart: {{ template "web.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
{{- else if .Values.zabbixweb.sslcert }}
  sslcert: |
{{- range $key, $value := default dict .Values.zabbixweb.sslcert }}
    {{ $key | snakecase }}={{ $value }}
{{- end }}
{{- end }}
{{- if .Values.zabbixweb.sslkey }}
  sslkey: |
{{ .Values.zabbixweb.sslkey  | indent 4 }}
{{- end }}
{{- if .Values.zabbixweb.dhparam }}
  dhparam: |
{{ .Values.zabbixweb.dhparam  | indent 4 }}
{{- end }}