---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "agent.fullname" . }}
  labels:
    app: {{ include "agent.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: zabbix-agent