{{- if gt (.Values.zabbixserver.replicaCount | int) 1 }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "zabbix.fullname" . }}-init-db-schema
  labels:
    app: {{ template "zabbix.fullname" . }}-init-db-schema
    app.kubernetes.io/name: init-db-schema
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-init-db-schema
    app.kubernetes.io/managed-by: {{ .Release.Service }}-init-db-schema
spec:
  template:
    spec:
      containers:
      - name: init-db-schema
        {{- if .Values.zabbix_image_tag }}
        image: {{ .Values.zabbixserver.image.repository }}:{{ .Values.zabbix_image_tag }}
        {{- else }}
        image: {{ .Values.zabbixserver.image.repository }}:{{ .Values.zabbixserver.image.tag }}
        {{- end }}
        env:
          {{- if .Values.postgresql.enabled }}
          - name: DB_SERVER_HOST
            value: {{ template "zabbix.fullname" . }}-postgresql
          - name: DB_SERVER_PORT
            value: {{ .Values.postgresql.service.port | quote }}
          {{- else if .Values.db_access.use_unified_secret }}
          - name: DB_SERVER_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db_access.unified_secret_name }}
                key: host
          - name: DB_SERVER_PORT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db_access.unified_secret_name }}
                key: port
                optional: true
          {{- else }}
          - name: DB_SERVER_HOST
            value: {{ .Values.db_access.db_server_host | quote }}
          - name: DB_SERVER_PORT
            value: {{ .Values.db_access.db_server_port | quote }}
          {{- end }}
          {{- if .Values.db_access.use_unified_secret }}
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db_access.unified_secret_name }}
                key: user
                optional: true
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db_access.unified_secret_name }}
                key: password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db_access.unified_secret_name }}
                key: dbname
                optional: true
          {{- else }}
          - name: POSTGRES_USER
            value: {{ .Values.db_access.postgres_user | quote }}
          - name: POSTGRES_PASSWORD
            {{- if .Values.db_access.postgres_password_secret }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db_access.postgres_password_secret }}
                key: {{ default "password" .Values.db_access.postgres_password_secret_key }}
            {{- else }}
            value: {{ .Values.db_access.postgres_password | quote }}
            {{- end }}
          - name: POSTGRES_DB
            value: {{ .Values.db_access.postgres_db | quote }}
          {{- end }}
        command:
          - "/bin/sh"
          - "-c"
          - 'sed -e "s/^exec \"\$@\"$/prepare_server/" -e "/^ *update_zbx_config$/d" /usr/bin/docker-entrypoint.sh >~/docker-entrypoint.sh && bash ~/docker-entrypoint.sh'
      restartPolicy: Never
{{- end}}
