{{- if gt (.Values.zabbixserver.replicaCount | int) 1 }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "zabbix.fullname" . }}-init-db-schema
  labels:
    app: {{ template "zabbix.fullname" . }}-init-db-schema
    app.kubernetes.io/name: init-db-schema
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-init-db-schema
    app.kubernetes.io/managed-by: {{ .Release.Service }}-init-db-schema
spec:
  template:
    spec:
      containers:
      - name: init-db-schema
        image: {{ .Values.zabbixserver.image.repository }}:{{ .Values.zabbixserver.image.tag }}
        env:
          {{- if .Values.postgresql.enabled }}
          - name: DB_SERVER_HOST
            value: {{ template "zabbix.fullname" . }}-postgresql
          - name: DB_SERVER_PORT
            value: {{ .Values.postgresql.service.port | quote }}
          {{- else if .Values.db_access.secret_name }}
          - name: DB_SERVER_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db_access.secret_name }}
                key: host
          - name: DB_SERVER_PORT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db_access.secret_name }}
                key: port
                optional: true
          {{- else }}
          - name: DB_SERVER_HOST
            {{- if .Values.db_access.DB_SERVER_HOST }}
            value: {{ .Values.db_access.DB_SERVER_HOST | quote }}
            {{- else }}
            value: {{ .Values.zabbixserver.DB_SERVER_HOST | quote }}
            {{- end }}
          - name: DB_SERVER_PORT
            {{- if .Values.db_access.DB_SERVER_PORT }}
            value: {{ .Values.db_access.DB_SERVER_PORT | quote }}
            {{- else }}
            value: {{ .Values.zabbixserver.DB_SERVER_PORT | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.db_access.secret_name }}
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db_access.secret_name }}
                key: user
                optional: true
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db_access.secret_name }}
                key: password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db_access.secret_name }}
                key: dbname
                optional: true
          {{- else }}
          - name: POSTGRES_USER
            {{- if .Values.db_access.POSTGRES_USER }}
            value: {{ .Values.db_access.POSTGRES_USER | quote }}
            {{- else }}
            value: {{ .Values.zabbixserver.POSTGRES_USER | quote }}
            {{ end }}
          - name: POSTGRES_PASSWORD
            {{- if .Values.db_access.POSTGRES_PASSWORD }}
            value: {{ .Values.db_access.POSTGRES_PASSWORD | quote }}
            {{- else if .Values.zabbixserver.POSTGRES_PASSWORD_SECRET }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.zabbixserver.POSTGRES_PASSWORD_SECRET }}
                key: {{ default "password" .Values.zabbixserver.POSTGRES_PASSWORD_SECRET_KEY }}
            {{- else }}
            value: {{ .Values.zabbixserver.POSTGRES_PASSWORD | quote }}
            {{- end }}
          - name: POSTGRES_DB
            {{- if .Values.db_access.POSTGRES_DB }}
            value: {{ .Values.db_access.POSTGRES_DB | quote }}
            {{- else }}
            value: {{ .Values.zabbixserver.POSTGRES_DB | quote }}
            {{- end }}
          {{- end }}
        command:
          - "/bin/sh"
          - "-c"
          - 'sed -e "s/^exec \"\$@\"$/prepare_server/" -e "/^ *update_zbx_config$/d" /usr/bin/docker-entrypoint.sh >~/docker-entrypoint.sh && bash ~/docker-entrypoint.sh'
      restartPolicy: Never
{{- end}}
