---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zabbix.fullname" . }}-server
  labels:
    app: {{ include "zabbix.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: {{ .Values.zabbixServer.service.type }}
  ports:
    - port: 10051
      targetPort: 10051
      name: zabbix-trapper
    - port: 10052
      targetPort: 10052
      name: zabbix-jmx
  selector:
    name: zabbix-server
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zabbix.fullname" . }}-web
  labels:
    app: {{ include "zabbix.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: {{ .Values.zabbixWeb.service.type }}
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    name: zabbix-web