{{- if .Values.zabbixJavaGatway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "zabbix.fullname" . }}-{{ .Values.zabbixJavaGatway.ZBX_JAVAGATEWAY }}
  labels:
    app: {{ template "zabbix.fullname" . }}-{{ .Values.zabbixJavaGatway.ZBX_JAVAGATEWAY }}
    app.kubernetes.io/name: {{ .Values.zabbixJavaGatway.ZBX_JAVAGATEWAY }}
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Values.zabbixJavaGatway.ZBX_JAVAGATEWAY }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}-{{ .Values.zabbixJavaGatway.ZBX_JAVAGATEWAY }}
    {{- if .Values.zabbixJavaGatway.deploymentLabels }}
    {{- toYaml .Values.zabbixJavaGatway.deploymentLabels | nindent 4 }}
    {{- end }}
  annotations:
    {{- range $key,$value := .Values.zabbixJavaGatway.deploymentAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.zabbixJavaGatway.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "zabbix.fullname" . }}-{{ .Values.zabbixJavaGatway.ZBX_JAVAGATEWAY }}
  template:
    metadata:
      annotations:
        {{- range $key,$value := .Values.zabbixJavaGatway.containerAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      labels:
        app: {{ template "zabbix.fullname" . }}-{{ .Values.zabbixJavaGatway.ZBX_JAVAGATEWAY }}
        app.kubernetes.io/name: {{ .Values.zabbixJavaGatway.ZBX_JAVAGATEWAY }}
        helm.sh/chart: {{ include "zabbix.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Values.zabbixJavaGatway.ZBX_JAVAGATEWAY }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}-{{ .Values.zabbixJavaGatway.ZBX_JAVAGATEWAY }}
        {{- if .Values.zabbixJavaGatway.containerLabels }}
        {{- toYaml .Values.zabbixJavaGatway.containerLabels | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "zabbix.serviceAccountName" . }}
      {{- with .Values.zabbixJavaGatway.extraPodSpecs }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.karpenter.enabled }}
      {{- with .Values.karpenter.labels }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if gt (len .Values.affinity) 0 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- else if .Values.zabbixWebService.podAntiAffinity }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Values.zabbixJavaGatway.ZBX_JAVAGATEWAY }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.zabbixJavaGatway.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.zabbixJavaGatway.ZBX_JAVAGATEWAY }}
          {{- if .Values.zabbixJavaGatway.resources }}
          resources:
            {{- toYaml .Values.zabbixJavaGatway.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.zabbixJavaGatway.image.tag }}
          image: "{{ .Values.zabbixJavaGatway.image.repository }}:{{ .Values.zabbixJavaGatway.image.tag }}"
          {{- else }}
          image: "{{ .Values.zabbixJavaGatway.image.repository }}:{{ .Values.zabbixImageTag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.zabbixJavaGatway.image.pullPolicy }}
          ports:
            - name: zabbix-java-gw
              containerPort: {{ .Values.zabbixJavaGatway.service.port }}
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: zabbix-java-gw
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: zabbix-java-gw
            timeoutSeconds: 3
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
          securityContext:
            {{- toYaml .Values.zabbixJavaGatway.securityContext | nindent 12 }}
          env:
            - name: ZBX_START_POLLERS
              value: {{ .Values.zabbixJavaGatway.ZBX_START_POLLERS | quote }}
            - name: ZBX_DEBUGLEVEL
              value: {{ .Values.zabbixJavaGatway.ZBX_DEBUGLEVEL | quote }}
            - name: ZBX_TIMEOUT
              value: {{ .Values.zabbixJavaGatway.ZBX_TIMEOUT | quote }}
            - name: ZBX_PROPERTIES_FILE
              value: {{ .Values.zabbixJavaGatway.ZBX_PROPERTIES_FILE | quote }}
            - name: ZABBIX_OPTIONS
              value: {{ .Values.zabbixJavaGatway.ZABBIX_OPTIONS | quote }}
            {{- range $item := .Values.zabbixJavaGatway.extraEnv }}
            - name: {{ $item.name }}
              value: {{ $item.value | quote }}
            {{- end }}
          {{- with .Values.zabbixJavaGatway.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      imagePullSecrets:
      {{- range .Values.zabbixJavaGatway.image.pullSecrets }}
        - name: {{ . | quote }}
      {{- end }}
      volumes:
      {{- with .Values.zabbixJavaGatway.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}