{{- if and .Values.zabbixServer.enabled (gt (.Values.zabbixServer.replicaCount | int) 1) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "zabbix.fullname" . }}-init-db-schema
  labels:
    app: {{ template "zabbix.fullname" . }}-init-db-schema
    app.kubernetes.io/name: init-db-schema
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-init-db-schema
    app.kubernetes.io/managed-by: {{ .Release.Service }}-init-db-schema
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - name: init-db-schema
        {{- if .Values.zabbixServer.image.tag }}
        image: "{{ .Values.zabbixServer.image.repository }}:{{ .Values.zabbixServer.image.tag }}"
        {{- else }}
        image: "{{ .Values.zabbixServer.image.repository }}:{{ .Values.zabbixImageTag }}"
        {{- end }}
        env:
          {{- include "zabbix.postgresAccess.variables" (list $ . "zabbix") | nindent 10 }}
          {{- range $item := .Values.zabbixServer.extraEnv }}
          - name: {{ $item.name }}
            value: {{ $item.value | quote }}
          {{- end }}
          - name: ZBX_AUTOHANODENAME
            value: "hostname"
          - name: ZBX_NODEADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        command:
          - "/bin/sh"
          - "-c"
          - 'sed -e "s/^exec \"\$@\"$/prepare_server/" -e "/^ *update_zbx_config$/d" /usr/bin/docker-entrypoint.sh >~/docker-entrypoint.sh && bash ~/docker-entrypoint.sh'
      restartPolicy: Never
{{- end }}
